### PR TITLE
Switched arguments to fix deprecation warning

### LINKED ISSUE #57: Deprecation warning Moment.js
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

### PR DESCRIPTION
**Pull request by martijnrusschen**
Fixes #57

### CODE REVIEW

File: react-datepicker.js [hunk 1]
```diff
@@ -272,7 +272,7 @@ var DatePicker = React.createClass({displayName: 'DatePicker',
       React.DOM.div(null, 
         DateInput({
           date: this.props.selected, 
-          dateFormat: this.props.dateFormat,
+          dateFormat: this.props.dateFormat,
```
Comment (michiel3) [inline react-datepicker.js]: White space boya?

Comment (lbekkema) [inline react-datepicker.js]: Whitespace is being added by Grunt, IIRC.

Comment (martijnrusschen) [inline react-datepicker.js]: We could add something like https://www.npmjs.com/package/grunt-trimtrailingspaces to avoid this.
