### PR TITLE
Fix for time selection not allowing other changes

### LINKED ISSUE #1295: After setting time or manual input can no longer inject new moment
bug

### Expected behavior
Should be able to manually edit time and then inject a new moment.

### Actual behavior
Editing the time manually or through the UI doesn't let you change the input through props.

### Steps to reproduce
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import moment from 'moment';

class App extends Component {

  constructor(props){
    super(props);
    this.state = {
      selected: moment().subtract(1,'months')
    };
    this.format = "LLL";
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <DatePicker
            dateFormat='MMMM DD, YYYY h:mm A'
            selected={this.state.selected}
            allowSameDay
            onChange={this.onChange}
            showTimeSelect
            timeIntervals={15}
            disabledKeyboardNavigation
        />
        <button type="button" onClick={this.onClick}>Change time to now</button>
      </div>
    );
  }

  onClick = () => {
    this.setState({selected: moment()});
  }

  onChange = (date) => {
    console.log(date.format(this.format));
    this.setState({selected: date});
  }
}

export default App;
```

### PR DESCRIPTION
**Pull request by tomtwttr**
Fixes #1295

### CODE REVIEW

File: src/index.jsx [hunk 1]
```diff
@@ -173,6 +173,7 @@ export default class DatePicker extends React.Component {
         highlightDates: getHightLightDaysMap(nextProps.highlightDates)
       });
     }
+    this.setState({ inputValue: null });
```
Comment (aij) [inline src/index.jsx]: I don't think it's a good idea to discard user input on *every* prop change.

As you can see from the failed test, this could result in discarding user input as they are typing.

File: test/timepicker_test.js [hunk 2]
```diff
@@ -7,20 +7,23 @@ import Time from "../src/time";
...
-    let onChangeMoment = null;
-    const onChange = m => {
-      onChangeMoment = m;
-    };
-    makeDatePicker(onChange);
+    renderDatePicker("February 28, 2018 4:43 PM");
     expect(getInputString()).to.equal("February 28, 2018 4:43 PM");
     setManually("February 28, 2018 4:45 PM");
-    expect(onChangeMoment.format("LLL")).to.equal("February 28, 2018 4:45 PM");
+    expect(getInputString()).to.equal("February 28, 2018 4:45 PM");
```
Comment (aij) [inline test/timepicker_test.js]: This test used to check the moment passed to `onChange`. Why shouldn't it do that any more?

File: test/timepicker_test.js [hunk 3]
```diff
@@ -7,20 +7,23 @@ import Time from "../src/time";
 
 describe("TimePicker", () => {
   let datePicker;
+  let div;
+  let format;
```
Comment (aij) [inline test/timepicker_test.js]: Why should this be a variable? Isn't it always going to be "LLL"?

File: src/index.jsx [hunk 4]
```diff
@@ -372,7 +373,7 @@ export default class DatePicker extends React.Component {
 
     this.props.onChange(changedDate);
     this.setOpen(false);
-    this.setState({ inputValue: changedDate.format(this.props.dateFormat) });
+    this.setState({ inputValue: null });
```
Comment (aij) [inline src/index.jsx]: This does seem like a good idea. :)

File: package.json [hunk 5]
```diff
@@ -2,7 +2,7 @@
   "author": "HackerOne",
   "name": "react-datepicker",
   "description": "A simple and reusable datepicker component for React",
-  "version": "1.2.2",
+  "version": "1.2.3",
```
Comment (aij) [inline package.json]: We usually bump the version when doing a release, not with every PR.

**Comment by tomtwttr** [comment]
Hey @aij, thanks for the feedback. I've updated the PR and I think this solution works nicely.

File: src/index.jsx (hunk 4 above)
Comment (tomtwttr) [reply src/index.jsx]: To be clear, I think this is correct. This was actually my addition in https://github.com/Hacker0x01/react-datepicker/commit/a72bc43be63a00f8719361256c18466df7c2fb58#diff-73642d587163f2eb4d72f0fa6ebfba02R375.

Before that change the time would not change at all. The reason is that the input state side effect ignores changes. Clearing the input state makes sense if you're selecting a time.

File: test/timepicker_test.js [hunk 6]
```diff
@@ -29,23 +31,42 @@ describe("TimePicker", () => {
...
   }
 
-  function makeDatePicker(onChange) {
-    datePicker = TestUtils.renderIntoDocument(
+  function renderDatePicker(string) {
+    return renderDatePickerFor(moment(string, "LLL", true));
+  }
+
+  function renderDatePickerFor(selected) {
+    datePicker = ReactDOM.render(
```
[the remark this answers is not in the document]
Comment (tomtwttr) [reply test/timepicker_test.js]: The is needed such that the same component will be used AKA componentWillReceiveProps. A TestUtils.renderIntoDocument will not work for that kind of test.

File: package.json [hunk 7]
```diff
@@ -2,7 +2,7 @@
   "author": "HackerOne",
   "name": "react-datepicker",
   "description": "A simple and reusable datepicker component for React",
-  "version": "1.2.2",
+  "version": "1.2.4",
```
[the remark this answers is not in the document]
Comment (tomtwttr) [reply package.json]: Is it possible to leave this and let this bump to 1.2.5? Internally here I published this version a private registry, and I don't know if I can overwrite this version with the one you guys do.

[the remark this answers is not in the document]
Comment (rafeememon) [reply package.json]: No, sorry; please leave the versioning to us and our build process.

**Comment by tomtwttr** [comment]
Reverted the version change as requested by @rafeememon

**Comment by rafeememon** [comment]
Thanks @tomtwttr

**Comment by tomtwttr** [comment]
You're welcome
