### PR TITLE
Fix #4290 and #4289: Time component scroll issue

### LINKED ISSUE #4290: Last item not fully visible when scrolling in time when using portalId in scrollable div
**Describe the bug**
Last item not fully visible when scrolling in time when using portalId in scrollable div

**To Reproduce**

```
() => {
  const [startDate, setStartDate] = useState(new Date('02-02=2023 06:00'));
  return (
  <div>
  <div id='test'></div>
    <DatePicker
      portalId={'test'}
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      showTimeSelect
    />
     </div>
  );
};
```

**Expected behavior**
Should show the full height of last time item.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows
- BrowserChrome
- Version react-datepicker 4.10.0

### PR DESCRIPTION
**Pull request by balajis-qb**
Closes https://github.com/Hacker0x01/react-datepicker/issues/4290 and https://github.com/Hacker0x01/react-datepicker/issues/4289

Summary
This PR addresses an issue where the Time component scroll position was not accurate to the selected time, especially when the last option in the Time list got selected.  The fix ensures that the time component scrolls to the correct selected time item.  This PR will also fix the issue #4289 where the selected time is not getting auto scrolled when we use portalId

Changes Made

- Added the scroll logic inside the `requestAnimationFrame` method to schedule the scroll position update, ensuring that it occurs after the next repaint, when the DOM should be updated.
- Ensures the availability of the list ref before using it inside `requestAnimationFrame` callback.  By checking the ref availability, the issue of rendering failures is resolved, particularly during testing with asynchronous behavior.
- Updated the `time_format_test.test.js` tests to reflect the changes made on the Time component, by adding `await waitFor(() => ...)`
 to wait for an element an element to appear in the DOM and then make assertions.

### CODE REVIEW

File: src/time.jsx [hunk 1]
```diff
@@ -60,21 +60,29 @@ export default class Time extends React.Component {
...
     // code to ensure selected time will always be in focus within time window when it first appears
-    this.list.scrollTop =
-      this.centerLi &&
-      Time.calcCenterPosition(
-        this.props.monthRef
-          ? this.props.monthRef.clientHeight - this.header.clientHeight
-          : this.list.clientHeight,
-        this.centerLi,
-      );
+    this.scrollToTheSelectedTime();
```
Comment (martijnrusschen) [inline src/time.jsx:63]: Thanks for extracting this logic

**Review by martijnrusschen — APPROVED** [review]
Thanks for the fix and extensive writeup.

**Comment by balajis-qb** [comment]
Thank you for the review and approving my PR
